# Generated by Django 2.1.2 on 2018-11-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitjstats', '0002_auto_20181109_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='height',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='weight',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitjstats.Workout'),
        ),
    ]
